sudo: required
services:
  - docker

before_install:
  - docker build -t marian2267/cant_say -f Dockerfile.dev .

script:
  - docker run marian2267/cant_say CI=true npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-104047360514"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"





